name: Build and test
env:
  GO_VERSION: 1.21.6
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-nocache:
    strategy:
      matrix:
        go-version: [ ${{ env.GO_VERSION }} ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    name: lint, test, and build
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Check for CRLF endings
        uses: erclu/check-crlf@v1

      - name: All tests
        run: go test -v ./...

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          version: "latest"